### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by pim-moeskops** [groepjeweb2aja/wandelapp_issues#12]
is het mogelijk om Javascript ServiceWorker te gebruiken in combinatie met caching?
Zie voorbeeld van Google: https://developers.google.com/web/fundamentals/codelabs/offline/

Als er geen internetconnectie is, werkt de app niet. Dit is niet handig als je bijvoorbeeld op de Veluwe loopt.
Graag offline beschikbaar maken.

**Comment by jeroenvanoers** [comment]
Is het mogelijk om Javascript ServiceWorker te gebruiken in combinatie met caching?
Zie voorbeeld van Google: https://developers.google.com/web/fundamentals/codelabs/offline/
